export const generateDownloadableQrCode = (cropId: string) => {
    // We use the ID to find the SVG element generated by react-qr-code
    const svg = document.getElementById(`qrcode-${cropId}`);
    const canvas = document.getElementById('qr-canvas') as HTMLCanvasElement;
    if (!svg || !canvas) {
        return;
    }

    const svgData = new XMLSerializer().serializeToString(svg);
    const ctx = canvas.getContext('2d');
    const img = new Image();
    img.onload = () => {
        canvas.width = img.width;
        canvas.height = img.height;
        ctx?.drawImage(img, 0, 0);
        const pngFile = canvas.toDataURL('image/png');
        const downloadLink = document.createElement('a');
        downloadLink.download = `crop-${cropId}.png`;
        downloadLink.href = pngFile;
        document.body.appendChild(downloadLink);
        downloadLink.click();
        document.body.removeChild(downloadLink);
    };
    img.src = 'data:image/svg+xml;base64,' + btoa(svgData);
};
